### ISSUE TITLE
The parsed JSON is undefined if an error occurs -  code is looking for error?

### ISSUE THREAD

**Issue by ngunder** [haljin/erlesy#1]
Pawel, are we sure that this is correct?

`d3.json("example_fsm.json", function(error, graph) {
  if (error) throw error;`

**Comment by haljin** [comment]
If an error occurs parsing the json (or it times out) we propagate the error further. In theory we could handle it doing something else but we don't right now. This is pretty standard, probably copy pasted from an example.
